//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportEvents.Models.Vis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Users = new HashSet<User>();
        }
    
        public int EventId { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeOfEvent { get; set; }
        public Nullable<System.DateTime> RepeatUntil { get; set; }
        public int GroupId { get; set; }
        public int CreatorId { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public int Repeat { get; set; }
        public int Interval { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
